### ISSUE TITLE
Replies with `Array` after searching and queuing a track

### ISSUE THREAD

**Issue by lessp** [Iteam1337/sonos-wejay#57]
Steps to reproduce:

`s <some-track>`
Press "Queue track"
Wejay returns with "Array".

![image](https://user-images.githubusercontent.com/17602389/65497574-c1e7fb80-deba-11e9-9aa5-f980190d16ec.png)

**Comment by believer** [comment]
Was fixes in https://github.com/Iteam1337/sonos-wejay/commit/71dbe87681821f4750f88b38e0d307f0a81c7d5c, but the code wasn't on the server yet. Updated it now!

https://github.com/Iteam1337/sonos-wejay/blob/98ff03abe189b5306f4927d902e30733d6ac5cf0/src/Routes.re#L85
