### ISSUE TITLE
Handle Spotify playlist URL

### ISSUE THREAD

**Issue by believer** [Iteam1337/sonos-wejay#69]
#68 fixes the ability to add Spotify playlist based on URI (spotify:playlist:id), but not URL (https://open.spotify.com/playlist/id). Make sure that the parser handle both URL and URI for tracks and playlists.

**Comment by martinloman** [comment]
Issue öppnad -> releasead på 2 min. This is black magic!  🎩

**Comment by believer** [comment]
Haha japp!
